export interface WritingPrompt {
    id: string;
    text: string;
    category: 'Gratitude' | 'Reflection' | 'Emotions' | 'Goals' | 'Fun';
}

export const WRITING_PROMPTS: WritingPrompt[] = [
    // ── Gratitude ──────────────────────────────────────────────────────────────
    { id: 'g1', category: 'Gratitude', text: 'What are three things you are grateful for today?' },
    { id: 'g2', category: 'Gratitude', text: 'Who made a positive difference in your life recently, and why?' },
    { id: 'g3', category: 'Gratitude', text: 'Describe a small moment from today that brought you joy.' },
    { id: 'g4', category: 'Gratitude', text: 'What is something about your body or health you appreciate?' },
    { id: 'g5', category: 'Gratitude', text: 'Name a skill or talent you have that you sometimes take for granted.' },
    { id: 'g6', category: 'Gratitude', text: 'What is one thing about your home or environment you are thankful for?' },
    { id: 'g7', category: 'Gratitude', text: 'Think of a challenge you overcame — what did it teach you?' },
    { id: 'g8', category: 'Gratitude', text: 'What is a book, song, or piece of art that enriched your life?' },
    { id: 'g9', category: 'Gratitude', text: 'What blessings from God are you most thankful for in this season of life?' },
    { id: 'g10', category: 'Gratitude', text: 'Which family members bring the most joy and gratitude to your heart right now?' },
    { id: 'g11', category: 'Gratitude', text: 'What wisdom or life lessons from your past are you especially grateful for?' },
    { id: 'g12', category: 'Gratitude', text: 'What small, unnoticed blessing from God did you experience today?' },
    { id: 'g13', category: 'Gratitude', text: 'For which answered prayer are you most thankful right now?' },
    { id: 'g14', category: 'Gratitude', text: 'What family tradition or memory fills you with gratitude?' },
    { id: 'g15', category: 'Gratitude', text: 'What quality in your spouse or partner are you grateful for after all these years?' },
    { id: 'g16', category: 'Gratitude', text: 'What lesson from your parents or grandparents are you thankful you learned?' },
    { id: 'g17', category: 'Gratitude', text: 'How has God shown faithfulness in your life that you now appreciate deeply?' },
    { id: 'g18', category: 'Gratitude', text: 'What simple pleasure in your daily life brings you gratitude in retirement?' },
    { id: 'g19', category: 'Gratitude', text: 'Who in your family has shown you the most grace, and why are you thankful?' },
    { id: 'g20', category: 'Gratitude', text: 'What part of your faith journey are you most grateful for today?' },

    // ── Reflection ─────────────────────────────────────────────────────────────
    { id: 'r1', category: 'Reflection', text: 'What was the most meaningful thing that happened this week?' },
    { id: 'r2', category: 'Reflection', text: 'If you could give your past self one piece of advice, what would it be?' },
    { id: 'r3', category: 'Reflection', text: 'What belief have you changed your mind about in the last year?' },
    { id: 'r4', category: 'Reflection', text: 'Describe a decision you made recently. Are you happy with it?' },
    { id: 'r5', category: 'Reflection', text: 'What habits are helping you most right now?' },
    { id: 'r6', category: 'Reflection', text: 'What is something you wish you had more time for?' },
    { id: 'r7', category: 'Reflection', text: 'How have you grown as a person in the past six months?' },
    { id: 'r8', category: 'Reflection', text: 'What would a perfect ordinary day look like for you?' },
    { id: 'r9', category: 'Reflection', text: 'What is one thing you keep putting off and why?' },
    { id: 'r10', category: 'Reflection', text: 'What is one of the greatest lessons life has taught you?' },
    { id: 'r11', category: 'Reflection', text: 'How has your relationship with God deepened over the years?' },
    { id: 'r12', category: 'Reflection', text: 'Share some of your favorite family memories from over the decades.' },
    { id: 'r13', category: 'Reflection', text: 'What wisdom would you like to pass on to your children or grandchildren?' },
    { id: 'r14', category: 'Reflection', text: 'How has your perspective on what truly matters changed since retirement?' },
    { id: 'r15', category: 'Reflection', text: 'Describe a time when you clearly felt God\'s guidance or provision.' },
    { id: 'r16', category: 'Reflection', text: 'What legacy do you hope to leave behind for your family?' },
    { id: 'r17', category: 'Reflection', text: 'In what ways has aging brought you greater wisdom or peace?' },
    { id: 'r18', category: 'Reflection', text: 'If you could tell your younger self one thing about faith and family, what would it be?' },
    { id: 'r19', category: 'Reflection', text: 'What is the biggest lesson you learned in life?' },
    { id: 'r20', category: 'Reflection', text: 'What advice would you give your 10-year-old self, 20-year-old self, or younger self?' },
    { id: 'r21', category: 'Reflection', text: 'What family traditions from your childhood do you still cherish?' },
    { id: 'r22', category: 'Reflection', text: 'How did you meet your spouse, and what made that moment special?' },
    { id: 'r23', category: 'Reflection', text: 'What values from your parents did you try to pass on to your own children?' },
    { id: 'r24', category: 'Reflection', text: 'What is one of your happiest childhood memories?' },
    { id: 'r25', category: 'Reflection', text: 'What hardships shaped you the most, and what did you learn from them?' },
    { id: 'r26', category: 'Reflection', text: 'Who influenced your faith the most, and how?' },
    { id: 'r27', category: 'Reflection', text: 'What accomplishment are you most proud of when you look back on your life?' },
    { id: 'r28', category: 'Reflection', text: 'What story from your family history would you most like to preserve?' },
    { id: 'r29', category: 'Reflection', text: 'How has your understanding of God changed throughout the different seasons of life?' },
    { id: 'r30', category: 'Reflection', text: 'What words of wisdom did you receive that changed the course of your life?' },
    { id: 'r31', category: 'Reflection', text: 'What is your favorite memory with your grandchildren or children?' },
    { id: 'r32', category: 'Reflection', text: 'What did you want to be when you grew up, and how did life compare?' },
    { id: 'r33', category: 'Reflection', text: 'What legacy of faith or love do you hope your family carries forward?' },
    { id: 'r34', category: 'Reflection', text: 'Describe a time you felt God\'s peace during a difficult season.' },
    { id: 'r35', category: 'Reflection', text: 'What is one thing you wish you had known earlier about marriage or parenting?' },
    { id: 'r36', category: 'Reflection', text: 'How have your prayers changed over the years?' },
    { id: 'r37', category: 'Reflection', text: 'What holiday memory from your family brings you the most warmth?' },
    { id: 'r38', category: 'Reflection', text: 'What lesson about forgiveness has life taught you?' },
    { id: 'r39', category: 'Reflection', text: 'Who was the most influential person in your spiritual journey?' },
    { id: 'r40', category: 'Reflection', text: 'What does a life well-lived look like to you now?' },
    { id: 'r41', category: 'Reflection', text: 'What family recipe or tradition would you want passed down forever?' },
    { id: 'r42', category: 'Reflection', text: 'How did becoming a parent or grandparent change your view of God?' },
    { id: 'r43', category: 'Reflection', text: 'What surprising joy has retirement brought you?' },
    { id: 'r44', category: 'Reflection', text: 'What Bible verse or truth has anchored you through the years?' },

    // ── Emotions ───────────────────────────────────────────────────────────────
    { id: 'e1', category: 'Emotions', text: 'How are you feeling right now, and what might have caused that feeling?' },
    { id: 'e2', category: 'Emotions', text: 'Describe a moment recently when you felt proud of yourself.' },
    { id: 'e3', category: 'Emotions', text: 'What is something that has been worrying you? Write it out fully.' },
    { id: 'e4', category: 'Emotions', text: 'When did you last feel completely at peace? What were you doing?' },
    { id: 'e5', category: 'Emotions', text: 'What emotion do you find hardest to express? Why?' },
    { id: 'e6', category: 'Emotions', text: 'Describe a fear you have been carrying. What is the worst realistic outcome?' },
    { id: 'e7', category: 'Emotions', text: 'Write a letter to yourself about something you need to forgive yourself for.' },
    { id: 'e8', category: 'Emotions', text: 'What relationships in your life bring you the most energy right now?' },
    { id: 'e9', category: 'Emotions', text: 'How do you feel when you reflect on the love within your family?' },
    { id: 'e10', category: 'Emotions', text: 'When do you feel most connected to God, and what emotions come with that?' },
    { id: 'e11', category: 'Emotions', text: 'Write about any peaceful acceptance you\'ve found in this stage of life.' },
    { id: 'e12', category: 'Emotions', text: 'What painful situation from your past do you now see God’s hand in?' },
    { id: 'e13', category: 'Emotions', text: 'When have you felt farthest from God, and what helped you draw near again?' },
    { id: 'e14', category: 'Emotions', text: 'What emotion arises when you think about your life legacy?' },
    { id: 'e15', category: 'Emotions', text: 'How does reflecting on family memories make you feel?' },
    { id: 'e16', category: 'Emotions', text: 'What regret do you need to bring before God for healing?' },
    { id: 'e17', category: 'Emotions', text: 'Describe a moment you felt overwhelming gratitude toward God.' },
    { id: 'e18', category: 'Emotions', text: 'What brings you the deepest sense of peace in your faith?' },
    { id: 'e19', category: 'Emotions', text: 'How do you feel when you share wisdom with younger generations?' },
    { id: 'e20', category: 'Emotions', text: 'What emotion do you experience most often when thinking about your life’s journey?' },

    // ── Goals ──────────────────────────────────────────────────────────────────
    { id: 'go1', category: 'Goals', text: 'What is one goal you want to achieve in the next 30 days?' },
    { id: 'go2', category: 'Goals', text: 'Where do you want to be in five years? Describe it in detail.' },
    { id: 'go3', category: 'Goals', text: 'What is one small step you can take today toward a bigger goal?' },
    { id: 'go4', category: 'Goals', text: 'What does success mean to you — not to others, but to you specifically?' },
    { id: 'go5', category: 'Goals', text: 'Name one thing you want to learn or get better at this month.' },
    { id: 'go6', category: 'Goals', text: 'What would you do if you knew you could not fail?' },
    { id: 'go7', category: 'Goals', text: 'What habits would the best version of yourself have?' },
    { id: 'go8', category: 'Goals', text: 'What is holding you back from your biggest goal right now?' },

    // ── Fun ────────────────────────────────────────────────────────────────────
    { id: 'f1', category: 'Fun', text: 'If you could live anywhere in the world for one year, where would it be?' },
    { id: 'f2', category: 'Fun', text: 'Describe your ideal weekend from start to finish.' },
    { id: 'f3', category: 'Fun', text: 'If you could have dinner with any three people in history, who would you choose?' },
    { id: 'f4', category: 'Fun', text: 'What fictional world would you most want to visit?' },
    { id: 'f5', category: 'Fun', text: 'If you could master any skill instantly, what would it be and why?' },
    { id: 'f6', category: 'Fun', text: 'Describe your dream job — no limits on what is possible.' },
    { id: 'f7', category: 'Fun', text: 'What is the most adventurous thing on your bucket list?' },
    { id: 'f8', category: 'Fun', text: 'If you wrote a book, what would it be about?' }
];

export const PROMPT_CATEGORIES = ['Gratitude', 'Reflection', 'Emotions', 'Goals', 'Fun'] as const;
export type PromptCategory = typeof PROMPT_CATEGORIES[number];