import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";
import ThemeProvider from '@/components/ThemeProvider';
import ThemeManager from '@/components/ThemeManager';

// ─── Font configuration ───────────────────────────────────────────────────────
// Fonts are loaded from /public/fonts/ to support offline builds.
// To download the font files, run: node scripts/download-fonts.js

const geistSans = localFont({
  variable: "--font-geist-sans",
  display: "swap",
  src: [
    { path: "../../public/fonts/Geist-Thin.woff2",     weight: "100", style: "normal" },
    { path: "../../public/fonts/Geist-Light.woff2",    weight: "300", style: "normal" },
    { path: "../../public/fonts/Geist-Regular.woff2",  weight: "400", style: "normal" },
    { path: "../../public/fonts/Geist-Medium.woff2",   weight: "500", style: "normal" },
    { path: "../../public/fonts/Geist-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "../../public/fonts/Geist-Bold.woff2",     weight: "700", style: "normal" },
  ],
});

const geistMono = localFont({
  variable: "--font-geist-mono",
  display: "swap",
  src: [
    { path: "../../public/fonts/GeistMono-Regular.woff2", weight: "400", style: "normal" },
    { path: "../../public/fonts/GeistMono-Medium.woff2",  weight: "500", style: "normal" },
    { path: "../../public/fonts/GeistMono-Bold.woff2",    weight: "700", style: "normal" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ThemeManager />
          {children}
        </Providers>
      </body>
    </html>
  );
}
